### ISSUE TITLE
 importlib.metadata.PackageNotFoundError: sotastream

### ISSUE THREAD

**Issue by thammegowda** [marian-nmt/sotastream#4]
Currently, we have these ways of installing sotastream:

* `pip install  -e .`  or `pip install .`    (after git clone and cd into the dir)
* `pip install git+https://github.com/marian-nmt/sotastream.git`

But it doesn't work for `export PYTHONPATH=path/to/sotastream`

```
sotastream/__init__.py:7: in <module>
    __version__ = metadata.version(__package__)
/usr/lib/python3.8/importlib/metadata.py:530: in version
    return distribution(distribution_name).version
/usr/lib/python3.8/importlib/metadata.py:503: in distribution
    return Distribution.from_name(distribution_name)
/usr/lib/python3.8/importlib/metadata.py:177: in from_name
    raise PackageNotFoundError(name)
E   importlib.metadata.PackageNotFoundError: sotastream
```

TODO: fix this error. remove importlib

**Comment by mjpost** [comment]
Maybe we should move `__version__` to the top-level package file? It's nice to be able to query the version via

```
import sotastream
sotastream.__version__
```

We could parse it from there for other purposes, too, so as to avoid the redundancy.

**Comment by thammegowda** [comment]
right, we should retain the ability to query `sotastream.__version__` 
Also, we want to specify version number at only one place (either in setup file OR in sotastream.__init__.py), to avoid one going out of sync with other.

since we are using pyproject.toml, we have a bit of inflexibility (cant write python regex to parse version number).
but fortunately, there seems to be an attempt to address this problem. 
Last time it didnt work as expected (it tried to import sotastream as package while its dependencies are not installed). 
I will try again with slightly different approach. 

Note to self: 
* docs: https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata
* use 'file' instead of 'attr'
